import React, { useState, useEffect, useMemo, useRef, useCallback } from "react";
// Integrations view — sponsor showcase

const INTEGRATIONS = [
  {
    id: 'veea', name: 'Veea Edge Nodes', category: 'Edge Compute',
    status: 'connected', sponsor: true,
    desc: 'Runtime is deployed on Veea edge hardware — inference, rule matching, and decoy generation all happen inside the customer perimeter. No prompts leave the building.',
    meta: { 'Latency': '4ms', 'Active nodes': '12 / 12', 'Build': 'mirage-edge v0.4.1', 'Tier': 'Production' },
    accent: 'oklch(0.72 0.16 195)',
    logoText: 'VEEA',
  },
  {
    id: 'splunk', name: 'Splunk Enterprise', category: 'SIEM',
    status: 'connected',
    desc: 'All detection events, decoy session transcripts, and attacker indicators forwarded to your Splunk index in CEF format.',
    meta: { 'Throughput': '142 ev/s', 'Index': 'mirage_security', 'Last batch': '2s ago' },
    accent: 'oklch(0.74 0.14 35)',
    logoText: 'SPL',
  },
  {
    id: 'datadog', name: 'Datadog', category: 'Observability',
    status: 'connected',
    desc: 'Metrics, traces, and the decoy-engagement timeline streamed to Datadog dashboards. Per-rule SLOs supported.',
    meta: { 'Account': 'ent-prod', 'Last metric': 'just now', 'Cost': '$0.12/h' },
    accent: 'oklch(0.72 0.14 295)',
    logoText: 'DD',
  },
  {
    id: 'ollama', name: 'Local Llama-3 (Ollama)', category: 'Decoy Model',
    status: 'connected',
    desc: 'Decoy responses generated by a local Llama-3-8B running on the Veea node — fully air-gapped, no external API calls.',
    meta: { 'Model': 'llama-3-8b-instruct.Q5_K_M', 'Hardware': 'Veea VHE-09', 'Mode': 'Air-gapped' },
    accent: 'oklch(0.74 0.15 150)',
    logoText: 'LL3',
  },
  {
    id: 'openai', name: 'OpenAI API Proxy', category: 'Real Model',
    status: 'disconnected',
    desc: 'Optional pass-through for real (non-attacked) traffic. Currently disabled — using on-prem only.',
    meta: { 'Reason': 'air-gap policy', 'Last connect': '14d ago' },
    accent: 'oklch(0.60 0.012 250)',
    logoText: 'GPT',
  },
  {
    id: 'pagerduty', name: 'PagerDuty', category: 'Incident',
    status: 'connected',
    desc: 'Critical-severity attack patterns trigger PagerDuty incidents to the on-call security rotation.',
    meta: { 'Service': 'mirage-sec-oncall', 'Routing': 'tier-2 escalation' },
    accent: 'oklch(0.74 0.16 60)',
    logoText: 'PD',
  },
  {
    id: 'slack', name: 'Slack', category: 'Notifications',
    status: 'connected',
    desc: 'Per-incident threads in #security-events with decoy transcript snippets and one-click trap-burn actions.',
    meta: { 'Workspace': 'acme-corp', 'Channel': '#security-events' },
    accent: 'oklch(0.74 0.14 320)',
    logoText: 'SLK',
  },
  {
    id: 'misp', name: 'MISP / OpenCTI', category: 'Threat Intel',
    status: 'connected',
    desc: 'Captured attacker indicators (IPs, payload hashes, TTPs) pushed upstream as STIX 2.1 objects.',
    meta: { 'Feed': 'mirage-honeypot', 'TLP': 'AMBER' },
    accent: 'oklch(0.72 0.14 250)',
    logoText: 'CTI',
  },
];

function IntegrationsView() {
  const counts = {
    connected: INTEGRATIONS.filter(i => i.status === 'connected').length,
    disconnected: INTEGRATIONS.filter(i => i.status === 'disconnected').length,
  };
  const veea = INTEGRATIONS.find(i => i.id === 'veea');
  const others = INTEGRATIONS.filter(i => i.id !== 'veea');

  return (
    <div>
      <div style={{ display: 'flex', alignItems: 'baseline', justifyContent: 'space-between', marginBottom: 14 }}>
        <div>
          <div style={{ fontSize: 18, fontWeight: 500, marginBottom: 2 }}>Integrations</div>
          <div className="mono mute" style={{ fontSize: 11 }}>
            {counts.connected} connected · {counts.disconnected} disconnected · MIRAGE plays well with the SOC stack you already run.
          </div>
        </div>
        <div style={{ display: 'flex', gap: 8 }}>
          <button className="btn"><Icon name="search" />Browse marketplace</button>
          <button className="btn primary"><Icon name="plus" />Add integration</button>
        </div>
      </div>

      {/* Veea spotlight */}
      <VeeaSpotlight veea={veea} />

      <div className="caps mute" style={{ margin: '18px 4px 10px' }}>Other integrations</div>
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(280px, 1fr))', gap: 12 }}>
        {others.map(i => <IntegrationCard key={i.id} integration={i} />)}
      </div>
    </div>
  );
}

function VeeaSpotlight({ veea }) {
  return (
    <div className="panel" style={{
      padding: 22,
      background: `linear-gradient(135deg, oklch(0.22 0.06 195 / 0.5), var(--panel) 60%)`,
      border: '1px solid oklch(0.42 0.10 195)',
      position: 'relative',
      overflow: 'hidden',
    }}>
      <div style={{
        position: 'absolute', top: -40, right: -40, width: 280, height: 280,
        background: 'radial-gradient(circle, oklch(0.62 0.16 195 / 0.18), transparent 70%)',
        pointerEvents: 'none',
      }} />
      <div style={{ display: 'flex', alignItems: 'flex-start', gap: 20, position: 'relative' }}>
        {/* Logo placeholder */}
        <div style={{
          width: 88, height: 88, borderRadius: 12,
          background: `linear-gradient(135deg, ${veea.accent}, oklch(0.50 0.10 195))`,
          display: 'grid', placeItems: 'center',
          fontFamily: 'var(--font-mono)', fontSize: 18, fontWeight: 600,
          color: 'var(--bg)',
          letterSpacing: '0.08em',
          boxShadow: '0 4px 16px oklch(0.40 0.10 195 / 0.4)',
          position: 'relative',
        }}>
          {veea.logoText}
          <div style={{
            position: 'absolute', bottom: 6, right: 6,
            width: 10, height: 10, borderRadius: '50%',
            background: 'var(--safe)',
            boxShadow: '0 0 8px var(--safe)',
          }} />
        </div>
        <div style={{ flex: 1 }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
            <div style={{ fontSize: 20, fontWeight: 500 }}>Veea Edge Nodes</div>
            <span className="pill" style={{ color: veea.accent, background: 'oklch(0.22 0.06 195 / 0.5)', borderColor: veea.accent }}>
              <span className="dot"></span>Infrastructure Partner
            </span>
            <Pill kind="safe">Connected</Pill>
          </div>
          <div className="mono mute" style={{ fontSize: 11, marginTop: 4 }}>edge-runtime / category: edge compute</div>
          <div style={{ marginTop: 10, fontSize: 13, color: 'var(--text-dim)', lineHeight: 1.55, maxWidth: 720 }}>
            The MIRAGE runtime ships as a Veea VHE container. Inference, rule matching, and decoy generation
            all execute <span style={{ color: 'var(--text)' }}>inside the customer perimeter</span> with sub-5ms swap latency —
            no prompts, no decoy transcripts, no attacker IOCs ever leave the building. The SIEM forwarder is the only
            egress, and it speaks your existing formats.
          </div>
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: 18, marginTop: 16 }}>
            <SpotlightStat label="Active edge nodes" value="12 / 12" accent="var(--safe)" />
            <SpotlightStat label="Prompt-swap latency" value="4ms" accent={veea.accent} />
            <SpotlightStat label="Runtime build" value="v0.4.1" />
            <SpotlightStat label="Data egress" value="0 bytes" accent="var(--safe)" />
          </div>
          <div style={{ display: 'flex', gap: 8, marginTop: 18 }}>
            <button className="btn primary"><Icon name="settings" />Configure cluster</button>
            <button className="btn"><Icon name="chart" />Node telemetry</button>
            <button className="btn"><Icon name="download" />Pull diagnostic</button>
          </div>
        </div>
      </div>
    </div>
  );
}

function SpotlightStat({ label, value, accent }) {
  return (
    <div>
      <div className="caps mute" style={{ fontSize: 10 }}>{label}</div>
      <div className="mono" style={{ fontSize: 20, marginTop: 2, color: accent || 'var(--text)' }}>{value}</div>
    </div>
  );
}

function IntegrationCard({ integration }) {
  const connected = integration.status === 'connected';
  return (
    <div className="panel" style={{ padding: 14, opacity: connected ? 1 : 0.72 }}>
      <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
        <div style={{
          width: 40, height: 40, borderRadius: 7,
          background: connected
            ? `linear-gradient(135deg, ${integration.accent}, oklch(from ${integration.accent} l c h / 0.5))`
            : 'var(--bg-2)',
          border: connected ? 'none' : '1px dashed var(--border)',
          display: 'grid', placeItems: 'center',
          fontFamily: 'var(--font-mono)', fontSize: 11, fontWeight: 600,
          color: connected ? 'var(--bg)' : 'var(--text-mute)',
          letterSpacing: '0.05em',
        }}>{integration.logoText}</div>
        <div style={{ flex: 1, minWidth: 0 }}>
          <div style={{ fontSize: 13, fontWeight: 500, whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>{integration.name}</div>
          <div className="mono mute" style={{ fontSize: 10 }}>{integration.category}</div>
        </div>
        {connected ? <Pill kind="safe">Connected</Pill> : <Pill kind="mute">Disconnected</Pill>}
      </div>
      <div style={{ fontSize: 11.5, color: 'var(--text-dim)', marginTop: 10, lineHeight: 1.55, minHeight: 48 }}>
        {integration.desc}
      </div>
      <div style={{ display: 'flex', flexDirection: 'column', gap: 4, marginTop: 10 }}>
        {Object.entries(integration.meta).slice(0, 3).map(([k, v]) => (
          <div key={k} style={{ display: 'flex', fontSize: 11 }}>
            <span className="mute" style={{ width: 100 }}>{k}</span>
            <span className="mono" style={{ color: connected ? 'var(--text)' : 'var(--text-mute)' }}>{v}</span>
          </div>
        ))}
      </div>
      <div style={{ marginTop: 12, display: 'flex', gap: 6 }}>
        {connected ? (
          <>
            <button className="btn" style={{ flex: 1, justifyContent: 'center', fontSize: 11 }}>Configure</button>
            <button className="btn" style={{ fontSize: 11 }}>Disconnect</button>
          </>
        ) : (
          <button className="btn primary" style={{ flex: 1, justifyContent: 'center', fontSize: 11 }}>Connect</button>
        )}
      </div>
    </div>
  );
}

window.IntegrationsView = IntegrationsView;
